apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausages-deployment
  annotations:
    argocd-image-updater.argoproj.io/image-list: berthengron/sausages
    argocd-image-updater.argoproj.io/berthengron/sausages.update-strategy: latest
spec:
  selector:
    matchLabels:
      app: sausages
  replicas: 2
  template:
    metadata:
      labels:
        app: sausages
    spec:
      containers:
      - name: sausages
        image: berthengron/sausages:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sausages-service
spec:
  selector:
    app: sausages
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
