apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausages-deployment
  labels:
    app: sausages
  annotations:
    argocd-image-updater.argoproj.io/image-list: alihop/sausages
    argocd-image-updater.argoproj.io/alihop-sausages.update-strategy: latest
spec:
  selector:
    matchLabels:
      app: sausages
  replicas: 2
  template:
    metadata:
      labels:
        app: sausages
    spec:
      containers:
      - name: sausages
        image: alihop/sausages:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: sausages
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
