name: Build Ionic App and Deploy Docker
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Ionic
        run: npm i -g @ionic/cli
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ionic build