name: Build Angular App and Deploy on Firebase
on:
  push:
    branches:
      - refactor

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Ionic
        run: npm i @ionic/cli
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: ionic build